# Generated by Django 5.2.7 on 2025-10-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('dob', models.DateField(max_length=10)),
                ('weight', models.FloatField(blank=True, max_length=5, null=True)),
                ('is_alive', models.BooleanField()),
            ],
        ),
    ]
