# Generated by Django 4.2.25 on 2025-10-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='animals/'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='takenVaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.takenvaccine'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.record'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.animal'),
        ),
        migrations.AlterField(
            model_name='takenvaccine',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.record'),
        ),
        migrations.AlterField(
            model_name='takenvaccine',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.vaccine'),
        ),
    ]
