# Generated by Django 4.2.25 on 2025-10-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_appointment_vaccine_alter_animal_owner_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='dob',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='last_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='lote',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='next_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
