# Generated by Django 4.2.25 on 2025-10-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_prescription_date_alter_anamnese_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='animal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.animal'),
        ),
    ]
