# Generated by Django 4.2.25 on 2025-10-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_appointment_animal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
