# Generated by Django 4.2.25 on 2025-10-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
