# Generated by Django 4.2.25 on 2025-10-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_appointment_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anamnese',
            new_name='Anamnesis',
        ),
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointments',
        ),
        migrations.RenameModel(
            old_name='Complaint',
            new_name='Complaints',
        ),
        migrations.RenameModel(
            old_name='Prescription',
            new_name='Prescriptions',
        ),
        migrations.RenameModel(
            old_name='Vaccine',
            new_name='Vaccines',
        ),
        migrations.RenameModel(
            old_name='Animal',
            new_name='Animals',
        ),
        migrations.RenameModel(
            old_name='Owner',
            new_name='Owners',
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.animals')),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.owners')),
            ],
        ),
    ]
