# Generated by Django 4.2.25 on 2025-10-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_rename_anamnese_anamnesis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='animal_id',
        ),
        migrations.RemoveField(
            model_name='takenvaccines',
            name='animal_id',
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='record_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.records'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='record_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.records'),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='record_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.records'),
        ),
        migrations.AddField(
            model_name='takenvaccines',
            name='record_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.records'),
        ),
    ]
